name: child workflow

on:
  push:
    branches:
      - main
      
jobs:  
  deploy-pr:
    name: pr_echo
    uses: ./.github/workflows/base.yml
    with:
      environment: pr
    secrets: inherit
  deploy-dev:
    needs: deploy-pr
    name: dev_echo
    uses: ./.github/workflows/base.yml
    with:
      environment: dev
    secrets: inherit
  deploy-stg:
    needs: deploy-dev
    name: stg_echo
    uses: ./.github/workflows/base.yml
    with:
      environment: stg
    secrets: inherit
  deploy-qa:
    needs: deploy-dev
    name: qa_echo
    uses: ./.github/workflows/base.yml
    with:
      environment: qa
    secrets: inherit
  deploy-prd:
    needs: deploy-stg
    name: prd_echo
    uses: ./.github/workflows/base.yml
    with:
      environment: prd
    secrets: inherit
